indent-width = 4
line-length = 200
target-version = "py39"

[lint]
preview = true
select = ["ANN", "E", "F", "I"]
ignore = []

[lint.per-file-ignores]
"./src/nuremics_studio/nuRemics_App.py" = ["ANN"]